on:
  push:
    branches:
      - master
jobs:
  main:
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Run beachball version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "tnc1997@virginmedia.com"
          git config --global user.name "Thomas Clark"
          git remote set-url origin https://tnc1997:"$GITHUB_TOKEN"@github.com/tnc1997/flutter-tfl-api-client.git
          BRANCH=bump-$(date +"%s")
          git checkout -b "$BRANCH"
          npx beachball bump
          VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed "s/[\",]//g" | tr -d "[[:space:]]")
          sed -i -e "s/version: .*/version: $VERSION/g" pubspec.yaml
          git add --all
          git commit --message "release: cut the v$VERSION release [skip ci]"
          git tag --annotate "tfl-api-client_v$VERSION" --message "tfl-api-client v$VERSION"
          git push --follow-tags origin HEAD:"$BRANCH"
          git checkout master
          git pull origin master
          git merge --no-edit "$BRANCH"
          git push --follow-tags origin master
          git branch --delete "$BRANCH"
          git push --delete origin "$BRANCH"
